// Finnish 3-letter word definitions
// Auto-generated for Piilosana word hunt game
const DEFS_FI={
aah:"huudahdus, ihmetys",
aan:"aa-kirjaimen taivutus",
aat:"aa-kirjaimet (mon.)",
abi:"ylioppilas, abiturientti",
abo:"Abo = Turku (ruots.)",
aha:"oivalluksen huudahdus",
aho:"metsän avoin paikka",
aie:"aikomus, suunnitelma",
ain:"aina (murt.)",
aio:"aikoa-verbi: en aio",
ais:"aisa (murt.)",
aja:"ajaa-verbi: aja!",
ajo:"ajaminen, kulkeminen",
aju:"ajurin lyhenne",
aku:"akku (puhek.)",
ala:"alue, kenttä; alaosa",
ale:"alennusmyynti",
ali:"alittaa: ali hinnan",
alv:"arvonlisävero",
amk:"ammattikorkeakoulu",
ane:"aneiden kauppa; pyyntö",
ani:"kovin, erittäin: ani harva",
ano:"anoa-verbi: ano lupaa",
apa:"apaatti, laiska olento",
ape:"apea, surullinen",
apu:"avustus, tuki",
ara:"arka (murt.); asuntorahasto",
aro:"kuiva ruohotasanko",
ase:"sota-ase, työkalu",
asu:"vaatetus; asua-verbi",
atk:"automaattinen tietojenkäsittely",
atp:"adenosiinitrifosfaatti",
auo:"auon, avata (murt.)",
avi:"ilmoitus, tiedote",
avo:"avoin: avoliitto",
avu:"avun taivutus",
bee:"b-kirjaimen nimi",
bet:"lyöntivetopeli",
bin:"binäärinen",
bit:"tiedon perusyksikkö",
bkt:"bruttokansantuote",
boa:"jättiläiskäärme",
buu:"buuaus, paheksunta",
bää:"lampaan ääni",
böö:"paheksunnan huudahdus",
cee:"c-kirjaimen nimi",
ces:"c-sävel",
cis:"korotettu c-sävel",
cup:"cup-turnaus",
dan:"taidon taso budolajeissa",
ddr:"It.-Saksan lyhenne",
dee:"d-kirjaimen nimi",
des:"alennettu d-sävel",
dia:"läpinäkyvä kuva, diaesitys",
dis:"korotettu d-sävel",
dkk:"Tanskan kruunu (valuutta)",
dna:"deoksiribonukleiinihappo",
don:"espanjalainen arvonimi",
duo:"kaksikko",
dvd:"digitaalinen videolevy",
ecu:"entinen EU-valuuttayksikkö",
edo:"edellinen, entinen (vanh.)",
eeg:"aivosähkökäyrä",
een:"ee-kirjaimen taivutus",
ees:"eteenpäin (murt.)",
efa:"vanha tilavuusmitta",
ege:"Egeanmeri",
ego:"minuus, minäkuva",
ein:"kieltomuoto: ein (saksa)",
eis:"korotettu e-sävel",
eka:"ensimmäinen (puhek.)",
ekg:"sydänsähkökäyrä",
eko:"ekologinen",
ekp:"Euroopan keskuspankki",
eks:"entinen: eksmies",
ele:"käsiliike, ilme",
eli:"selittävä konjunktio; olla-verbi",
elo:"elonkorjuu; elokuu",
ely:"elinkeino-, liikenne- ja ympäristökeskus",
elä:"elää-verbi; kehotus: elä nyt!",
emi:"emä-, kantalevyn puoli",
emo:"emotionaalinen; emolevy",
emt:"en muista/tiedä (puhek.)",
emu:"lentokyvytön australianlintu",
emä:"naaraspuolinen eläin",
eno:"äidin veli (murt./karj.)",
enä:"enää: ei enää",
eos:"aamunkoitto (mytol.)",
epo:"erytropoietiini (doping)",
epä:"etuliite: ei-, epä-",
eri:"erilainen, toisenlainen",
ero:"erottautuminen; eroaminen",
erä:"osuus; metsästysretki",
esi:"etuliite: edeltävä",
eta:"kreikan kirjain η",
eto:"etoa, inhoa (murt.)",
etu:"hyöty, etu; etuosa",
etä:"etuliite: kaukaa, etätyö",
eve:"evenki-kansa",
evo:"evoluutio (lyhenne)",
evä:"kalan evä",
ewe:"Länsi-Afrikan kansa/kieli",
exä:"entinen puoliso (puhek.)",
fan:"ihailija, kannattaja",
fes:"alennettu f-sävel",
fii:"f-kirjaimen nimi",
fis:"korotettu f-sävel",
gay:"homoseksuaali",
gee:"g-kirjaimen nimi",
ges:"alennettu g-sävel",
gin:"katajanmarjaviina",
gis:"korotettu g-sävel",
gnu:"afrikkalainen antilooppi",
gon:"kulman mittayksikkö",
got:"goottikieli, -kansa",
haa:"haistaa; haukkoa henkeä",
hae:"hakea-verbi: hae!",
hah:"pilkallinen nauru",
hai:"petokala",
hau:"haukkaus",
heh:"naurua ilmaiseva huudahdus",
hei:"tervehdys",
hen:"kana (engl.)",
hep:"huudahdus: hep hep!",
het:"heti (murt.)",
hia:"hiertää; hiokas",
hie:"hietikko; hieno (murt.)",
hih:"hihitys, nauru",
hik:"hikka; hikoilla",
hio:"hioa-verbi: hio terää",
hip:"hip hip hurraa!",
his:"sihahdus, hissi",
hiv:"HI-virus",
hlö:"henkilö (lyhenne)",
hmh:"epäröivä äännähdys",
hmm:"mietiskelevä äännähdys",
hoe:"hokea: hoe samaa",
hoi:"huomion herättäminen",
hoo:"rauhoittelu: hoo hoo",
hop:"hypähdys: hop!",
hox:"huomautus (puhek.)",
hpy:"hyvää päivänjatkoa",
hra:"herra (lyhenne)",
hrr:"hevosen korskuminen",
hsl:"Helsingin seudun liikenne",
huh:"helpotuksen huudahdus",
hui:"pelästyksen huudahdus",
hus:"Helsingin yliopistollinen sairaala",
hyh:"halveksunnan äännähdys",
hyi:"inhon huudahdus",
hys:"hiljennys: hys!",
hyö:"he (murt.)",
häh:"hämmästyksen huudahdus",
hän:"kolmannen persoonan pronomini",
hää:"häät, avioliittojuhla",
höh:"vähättelevä huudahdus",
idä:"idätä-verbi",
ien:"ikenen taivutus",
ies:"valjasosa; iestää",
iha:"ihana (murt.)",
iho:"kehon ulkokerros",
iik:"pelästyksen huudahdus",
iit:"ii-kirjaimen monikko",
iki:"iki-: ikivanha, ikuinen",
ikä:"elinvuodet, vanhuus",
ile:"ilettää, iljettää",
ilo:"onni, riemu",
ime:"imeä-verbi: ime!",
imi:"imeä-verbi: imi",
imu:"imeminen, imuvoima",
ira:"kiukku, suuttumus",
iro:"ironia (lyhenne)",
isi:"isä (hellittelymuoto)",
iso:"suuri",
isä:"miespuolinen vanhempi",
ite:"itse (murt.)",
iti:"itää-verbi: siemen iti",
itu:"alkio, verso",
itä:"ilmansuunta; idän suunta",
iva:"pilkka, piikittely",
ivy:"kasvisuku (muratti)",
iän:"ikä-sanan taivutus",
iät:"ikä-sanan monikko: iät ajat",
jaa:"jatkaa: jaa jaa; jakaa",
jae:"jakaa-verbi: jae!",
jat:"jatke, jatkos",
jee:"ilon huudahdus",
jep:"myöntävä äännähdys",
jes:"onnistumisen huudahdus",
jhk:"jokin (lyhenne)",
jii:"kehotus: jii!",
jin:"yin (kiinalainen käsite)",
jkn:"jonkin (lyhenne)",
jku:"Jyväskylän yliopisto",
jne:"ja niin edelleen",
jnk:"jonkin (lyhenne)",
jod:"heprealainen kirjain",
joi:"juoda-verbi: joi maitoa",
joo:"kyllä (puhek.)",
jos:"ehtoa ilmaiseva konjunktio",
jtk:"jotakin (lyhenne)",
juo:"juoda-verbi: juo!",
juu:"kyllä (puhek.)",
jäi:"jäädä-verbi: jäi kotiin",
jää:"jäätynyt vesi",
jöö:"säälin huudahdus",
kaa:"kaataa (murt.)",
kaf:"heprealainen kirjain",
kai:"kai = luultavasti",
kao:"kaota, kadota (murt.)",
kap:"kapasiteetti (lyhenne)",
kas:"katso: kas vain!",
kat:"katsella (murt.)",
kea:"uusiseelantilainen papukaija",
ken:"kuka (vanh./runok.)",
kho:"kiinalainen kirjoitus",
kht:"tilintarkastaja (lyhenne)",
kii:"kiivas; kiihtyvä",
kim:"kimchi; kimpoilla",
kin:"partikkeli: minäkin",
kir:"kirjoittaa (lyhenne)",
kis:"kissa (puhek.)",
kit:"kitti, tiivistemassa",
kko:"kirkko (lyhenne)",
kkp:"keskuspankki (lyhenne)",
klo:"kello (lyhenne)",
knk:"kansanedustaja (lyhenne)",
koe:"testi, kokeilu",
koi:"koi-perhonen; koi-karppi",
kok:"kokoomus (lyhenne)",
kol:"kolkka; kolme (murt.)",
koo:"koota-verbi",
kop:"koputtaa-ääni",
kot:"koti (murt.)",
kph:"kylpyhuone (lyhenne)",
kpl:"kappale (lyhenne)",
krp:"keskusrikospoliisi",
krt:"kerta (lyhenne)",
ktm:"kauppatieteiden maisteri",
kui:"kuinka (murt.)",
kun:"kun-konjunktio",
kut:"kutoa-verbi (murt.)",
kuu:"Maan luonnollinen satelliitti",
kyl:"kyllä (murt.)",
kyy:"myrkyllinen käärme",
kyä:"kyllä (murt.)",
käy:"käydä-verbi: käy istumaan",
köh:"yskäisy",
köö:"köyhä (puhek.)",
lao:"laosilainen kieli/kansa",
led:"valodioodi",
lee:"tuulensuoja, suojaisa paikka",
lei:"Romanian valuutta",
leu:"Romanian valuutta",
lev:"Bulgarian valuutta",
lie:"liekki; lienee",
loi:"luoda-verbi: loi uutta",
los:"Los Angeles",
lsd:"lysergihappodietyyliamidi",
ltk:"lautakunta (lyhenne)",
lue:"lukea-verbi: lue!",
luo:"luoda-verbi: luo!",
luu:"luukudos, skeletti",
lux:"valon voimakkuuden yksikkö",
lvi:"lämpö, vesi, ilmastointi",
lyö:"lyödä-verbi: lyö!",
löi:"lyödä-verbi: löi palloa",
maa:"maaperä; valtio",
mar:"markka (lyhenne)",
mau:"mau-rotu (kissa)",
max:"maksimi, enintään",
mee:"mennä-verbi: mee (murt.)",
mem:"meemi (internet)",
mep:"europarlamentaarikko",
met:"metallinen (lyhenne)",
mie:"minä (murt.)",
min:"minimi; minuutti",
mit:"mitata (murt.)",
miä:"minä (murt.)",
mlk:"maalaiskunta (lyhenne)",
mml:"maanmittauslaitos",
moa:"sukupuuttoon kuollut jättilintu",
moi:"epämuodollinen tervehdys",
mot:"moottori; motto",
mrd:"miljardi (lyhenne)",
mtk:"maa- ja metsätaloustuottajain keskusliitto",
mua:"minua (puhek.)",
mun:"minun (puhek.)",
mut:"mutta (puhek.)",
muu:"toinen, erilainen",
myi:"myydä-verbi: myi auton",
myy:"kreikan kirjain μ; myydä",
myö:"me (murt.)",
mää:"lampaan ääni",
möi:"möyriä; myydä (murt.)",
naa:"naata, nahata (murt.)",
nai:"naida-verbi: nai",
nam:"herkullisen huudahdus",
nea:"neandertalinihminen",
nee:"omaa sukua (syntynyt)",
nel:"neljä (murt.)",
net:"internet, verkko",
nii:"niin (puhek.)",
nim:"nimimerkki (lyhenne)",
nkt:"nykytaiteen keskus (lyhenne)",
noh:"no niin (murt.)",
noi:"nuo (murt.)",
nol:"nolla (murt.)",
nsk:"naissivistysseura (lyhenne)",
nti:"neiti (lyhenne)",
nun:"nunna (vanh.)",
nuo:"nuo-pronomini",
nyi:"nyitä, nykiä (murt.)",
nyt:"tällä hetkellä",
nyy:"lankakerä, nyytinkantaja",
näe:"nähdä-verbi: en näe",
näy:"näyttää-verbi: näy!",
nää:"sinä/te (puhek.)",
nöf:"sian ääni",
oaj:"opettajien ammattijärjestö",
oan:"oa-tavun taivutus",
oas:"oasis, keidas",
oat:"oa-tavut (mon.)",
ohi:"sivuitse, ohi",
oho:"yllätyksen huudahdus",
oin:"oinas-sanan taivutus",
oio:"oiota, oikaista",
ois:"olisi (puhek.)",
oja:"vesioja, kaivanto",
oka:"vanha painomitta (~1,3 kg)",
ole:"olla-verbi: ole!",
oli:"olla-verbi: oli",
olo:"tunne, tila; oleskelu",
oma:"itselle kuuluva",
omi:"omia-verbi: omi kaiken",
oot:"olet (puhek.)",
ope:"opettaja (puhek.)",
opi:"oppia-verbi: opi!",
opo:"opinto-ohjaaja",
ora:"piikki, oka; suonikudos",
ori:"uroshevonen",
oro:"viikatteen teroitin",
osa:"osuus, pala",
ost:"ostaa (murt.)",
osu:"osua-verbi: osu!",
ota:"ottaa-verbi: ota!",
ote:"pitävä ote; katkelma",
out:"ulkona (engl.); vanhentunut",
ovi:"sisäänkäynti",
oyj:"julkinen osakeyhtiö",
paa:"paadata, painaa (murt.)",
pah:"halveksunnan huudahdus",
pai:"painaa-verbi (murt.); paita",
pam:"iskuääni; palvelualojen liitto",
par:"pari (murt.)",
pas:"passi; paha (murt.)",
pee:"p-kirjaimen nimi",
pen:"penikulma; peni (murt.)",
per:"per = kohti; peruuttaa",
pet:"pettää-verbi (murt.)",
pia:"pian (murt.)",
pii:"alkuaine (Si); piikivi",
piä:"päätä, pää (murt.)",
pkk:"kurdien työväenpuolue",
pkt:"paikallinen (lyhenne)",
pms:"premenstruaalinen oireyhtymä",
pop:"musiikkityyli",
pro:"ammattilainen; puolesta",
pst:"hiljaa! (kuiskaus)",
pub:"olutravintola",
pue:"pukea-verbi: pue!",
puh:"puhelin (lyhenne)",
pui:"puida-verbi: pui viljaa",
pum:"pamaus-ääni",
pus:"pusu (puhek.)",
put:"putata, pudota (murt.)",
puu:"puukasvi; puuaines",
pyh:"vähättelevä huudahdus",
pyi:"pyyhin (murt.)",
pyj:"pyjama (puhek.)",
pyy:"metsäkanalintu",
pää:"kallon yläosa; loppu",
pöh:"turhautumisen äännähdys",
pöö:"vähättelevä äännähdys",
qof:"heprealainen kirjain",
rae:"jääkide; rakeen taivutus",
rap:"musiikkityyli",
rkl:"reserviläisliitto",
rkp:"ruotsalainen kansanpuolue",
rna:"ribonukleiinihappo",
rok:"rokki, rock-musiikki",
ruk:"reserviupseerikoulu",
rva:"rouva (lyhenne)",
ryi:"ryijy (murt.)",
räi:"räikeä (murt.)",
röh:"röhkäisy",
saa:"saada-verbi: saa; saamelaiset",
sai:"saada-verbi: sai",
sak:"Saksa (lyhenne)",
san:"sana (murt.)",
sax:"saksofoni (puhek.)",
sdp:"sosiaalidemokraattinen puolue",
see:"s-kirjaimen nimi; seepra (murt.)",
seh:"sellainen (murt.)",
sei:"sei-valas; seistä (murt.)",
sen:"se-pronominin genetiivi",
ser:"seri, sarja (murt.)",
sia:"sikaa (murt.)",
sie:"sinä (murt.)",
sii:"siitä (murt.)",
sit:"sitten (puhek.)",
siä:"sinä (murt.)",
skp:"kommunistinen puolue (lyhenne)",
sks:"suomalaisen kirjallisuuden seura",
sky:"taivas (engl.)",
smp:"suomen maaseudun puolue",
sns:"sosiaali- ja terveysministeriö",
snt:"sentti (lyhenne)",
soi:"soida-verbi: soi kellot",
sok:"sokka; sokea (murt.)",
son:"sonni; hän (murt.)",
soo:"suota (murt.)",
spr:"punainen risti (lyhenne)",
srk:"seurakunta (lyhenne)",
ssa:"inessiivipääte: -ssa/-ssä",
stt:"Suomen tietotoimisto",
sua:"sinua (puhek.)",
sui:"sukeltaa: sui veteen",
sun:"sinun (puhek.)",
suo:"kosteikko; suoda: suo anteeksi",
sus:"suhahdus, suhina",
sut:"sutia, sotkea; suti (murt.)",
suu:"suuaukko",
syt:"syttyä (murt.)",
syy:"peruste, aihe; syksy",
syö:"syödä-verbi: syö!",
säe:"runon rivi",
sää:"ilmasto, ilma",
söi:"syödä-verbi: söi",
taa:"takaa, taempana (murt.)",
tae:"taipua, taivastellaan (murt.)",
tag:"merkintä, tunniste",
tai:"tai-konjunktio; taimen",
tao:"kiinalainen filosofia",
tau:"kreikan kirjain τ",
tav:"tavallinen (lyhenne)",
tea:"tee (juoma); teatteritaide",
tee:"kuuma juoma; golf-alusta",
teo:"teologinen (lyhenne)",
tes:"työehtosopimus",
tet:"työelämään tutustuminen",
tic:"tietokoneohjattu (lyhenne)",
tie:"kulkuväylä",
tii:"tiivis; tiistai (murt.)",
tit:"titteli (murt.)",
tiu:"tiuku, tiukka (murt.)",
tlk:"tölkki (lyhenne)",
toe:"torua, tokia (murt.)",
toi:"tuoda-verbi: toi lahjan",
tom:"tomaatti (lyhenne)",
top:"huippu, paras",
tor:"torstai (murt.)",
tri:"triathlon (lyhenne)",
tse:"tsetseekärpänen",
tsh:"Tšekin valuutta",
tue:"tukea-verbi: tue!",
tul:"tulo (murt.)",
tuo:"se, tuo; tuoda-verbi",
tus:"tuska; tuskin (murt.)",
tuu:"tulee (murt.)",
työ:"ansiotyö, aherrus",
täh:"hämmästyksen äännähdys",
täi:"loishyönteinen",
tän:"tämän (puhek.)",
tää:"tämä (puhek.)",
udi:"kaukasian kieli",
ufo:"tuntematon lentävä esine",
uho:"uhkaileva puhe",
uin:"uida-verbi: uin järvessä",
uit:"uida-verbi: uit (murt.)",
ujo:"arka, häveliäs",
uju:"ujuttaa (murt.)",
ukk:"Urho Kekkonen; isoisä (murt.)",
ula:"ulappa (murt.)",
ume:"Ruotsin kaupunki Umeå",
uni:"nukkuminen, unen tila",
ups:"pienen mokan huudahdus",
ura:"ammattitie, elämänura",
uro:"uros, miehekäs; ontelo",
usa:"Amerikan yhdysvallat",
utu:"ohut sumu",
uun:"uuni-sanan taivutus",
uus:"uusi-sanan taivutus",
uut:"uutiset (murt.)",
uve:"uvea, silmän osa",
vai:"vai-konjunktio; vaiko",
vau:"ihailun huudahdus",
vav:"heprealainen kirjain",
vee:"v-kirjaimen nimi",
vei:"viedä-verbi: vei mukanaan",
vek:"vekki, laskos",
via:"kautta (lat.)",
vie:"viedä-verbi: vie!",
vii:"viini (murt.); viisi (murt.)",
vip:"tärkeä henkilö",
vko:"viikko (lyhenne)",
voi:"maitorasva; voi-huudahdus",
vpk:"vapaapalokunta",
vrk:"vuorokausi (lyhenne)",
vrt:"vertaa (lyhenne)",
vtt:"valtion teknillinen tutkimuskeskus",
vuh:"tuulen suhahdus",
vuo:"vuoto; vuosi (murt.)",
vyö:"lannevyö",
wau:"ihailun huudahdus",
web:"verkko, internet",
wok:"aasialainen paistinpannu",
www:"world wide web",
xtc:"huumausaine (ekstaasi)",
yap:"Tyynenmeren saari",
yhe:"yheys, yhteys (murt.)",
yhä:"edelleen, vieläkin",
yin:"kiinalainen vastavoimapari",
yks:"yksi (puhek.)",
yle:"Yleisradio",
yli:"yli, yläpuolella",
ylä:"etuliite: ylä-, yläpuolinen",
ysi:"numero yhdeksän (puhek.)",
ytf:"yleisturvallisuusmaksu",
yty:"yritys (murt.)",
yxi:"yksi (vanh. kirjoitusasu)",
yyn:"yy-kirjaimen taivutus",
yyt:"yy-kirjaimet (mon.)",
yäk:"jakki (eläin)",
yök:"oksennusreaktio; yökerhon lyhenne",
yön:"yö-sanan genetiivi",
yöt:"yö-sanan monikko",
zen:"japanilainen meditaatioperinne",
zet:"z-kirjaimen nimi",
äes:"maanmuokkaustyökalu",
äks:"x-kirjaimen nimi",
äly:"älykkyys, viisaus",
älä:"kielto: älä tee!",
äng:"äng-äänne (ŋ)",
äsh:"kiusaantumisen huudahdus",
ääh:"epäröinnin äännähdys",
ääk:"inhon äännähdys",
ään:"ääni-sanan taivutus",
äät:"ääni-sanan monikko",
öin:"öisin, yöaikaan",
öky:"rikas, ylellinen (puhek.)",
ökö:"iljettävä (puhek.)",
öty:"huono juttu (puhek.)",
ööh:"epäröinnin äännähdys",
öön:"öö-kirjaimen taivutus",
ööt:"öö-kirjaimet (mon.)",
};
export default DEFS_FI;
